version: 2.1
orbs:
  windows: circleci/windows@5.1.1

jobs:
  build-on-unix:
    type: build
    docker:
      - image: cimg/rust:1.92.0
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential pkg-config
      - run: sudo apt-get install -y libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libx11-dev libwayland-dev libxkbcommon-dev
      - run: sudo apt-get install -y libfontconfig1-dev libfreetype6-dev
      - run: sudo apt-get install -y libasound2-dev
      - run: sudo apt-get install -y libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavdevice-dev libavfilter-dev
      - checkout
      - run: cargo build --release
      - store_artifacts:
          path: CIRCLE_WORKING_DIRECTORY/target/release/mapmap
          destination: linux-release
  build-on-macos:
    type: build
    macos:
      xcode: "26.2.0"
    steps:
      - run: brew install ffmpeg
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - checkout
      - run: cargo build --release
      - store_artifacts:
          path: CIRCLE_WORKING_DIRECTORY/target/release/mapmap
          destination: macos-release
  build-on-windows:
    type: build
    executor: windows/server-2025-cuda
    steps:
      - run: winget install --source winget --exact --id Microsoft.VisualStudio.2022.Community --override "--passive --config ${CIRCLE_WORKING_DIRECTORY}\wdk.vsconfig"
      - run:
          command: |
            curl https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe -o rustup-init.exe
            .\rustup-init.exe -vy
      - run: cargo build --release
      - store_artifacts:
          path: CIRCLE_WORKING_DIRECTORY/target/release/mapmap.exe
          destination: windows-release

workflows:
  binary_build:
    jobs:
      - build-on-unix
      - build-on-macos
      - build-on-windows